/********************************************************************************
** Form generated from reading UI file 'syszuxpinyin.ui'
**
** Created by: Qt User Interface Compiler version 5.11.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SYSZUXPINYIN_H
#define UI_SYSZUXPINYIN_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDialog>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_Dialog
{
public:
    QLineEdit *lineEdit_window;
    QPushButton *pushButton_u;
    QPushButton *pushButton_t;
    QPushButton *pushButton_y;
    QPushButton *pushButton_i;
    QPushButton *pushButton_q;
    QPushButton *pushButton_zuokuo;
    QPushButton *pushButton_p;
    QPushButton *pushButton_r;
    QPushButton *pushButton_youkuo;
    QPushButton *pushButton_w;
    QPushButton *pushButton_o;
    QPushButton *pushButton_e;
    QPushButton *pushButton_j;
    QPushButton *pushButton_g;
    QPushButton *pushButton_h;
    QPushButton *pushButton_k;
    QPushButton *pushButton_a;
    QPushButton *pushButton_quote;
    QPushButton *pushButton_semicolon;
    QPushButton *pushButton_f;
    QPushButton *pushButton_enter;
    QPushButton *pushButton_s;
    QPushButton *pushButton_l;
    QPushButton *pushButton_d;
    QPushButton *pushButton_m;
    QPushButton *pushButton_b;
    QPushButton *pushButton_n;
    QPushButton *pushButton_comma;
    QPushButton *pushButton_z;
    QPushButton *pushButton_splash;
    QPushButton *pushButton_v;
    QPushButton *pushButton_x;
    QPushButton *pushButton_period;
    QPushButton *pushButton_c;
    QPushButton *pushButton_shift;
    QPushButton *pushButton_whitespace;
    QPushButton *pushButton_up;
    QPushButton *pushButton_backsplash;
    QPushButton *pushButton_left;
    QPushButton *pushButton_right;
    QPushButton *pushButton_down;
    QPushButton *pushButton_n2;
    QPushButton *pushButton_is_hanzi;
    QPushButton *pushButton_ok;
    QPushButton *pushButton_hanzi_7;
    QPushButton *pushButton_hanzi_5;
    QPushButton *pushButton_hanzi_6;
    QPushButton *pushButton_hanzi_8;
    QPushButton *pushButton_hanzi_4;
    QPushButton *pushButton_hanzi_2;
    QPushButton *pushButton_hanzi_3;
    QPushButton *pushButton_hanzi_left;
    QPushButton *pushButton_hanzi_right;
    QPushButton *pushButton_hanzi_1;
    QLineEdit *lineEdit_pinyin;
    QPushButton *pushButton_n3;
    QPushButton *pushButton_backspace;
    QPushButton *pushButton_n0;
    QPushButton *pushButton_n1;
    QPushButton *pushButton_n6;
    QPushButton *pushButton_deng;
    QPushButton *pushButton_gang;
    QPushButton *pushButton_n5;
    QPushButton *pushButton_n7;
    QPushButton *pushButton_n8;
    QPushButton *pushButton_n4;
    QPushButton *pushButton_n9;

    void setupUi(QDialog *Dialog)
    {
        if (Dialog->objectName().isEmpty())
            Dialog->setObjectName(QStringLiteral("Dialog"));
        Dialog->resize(1133, 660);
        Dialog->setStyleSheet(QLatin1String("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);"));
        lineEdit_window = new QLineEdit(Dialog);
        lineEdit_window->setObjectName(QStringLiteral("lineEdit_window"));
        lineEdit_window->setGeometry(QRect(40, 0, 631, 60));
        lineEdit_window->setMinimumSize(QSize(0, 60));
        QFont font;
        font.setFamily(QStringLiteral("Noto Sans S Chinese"));
        font.setPointSize(15);
        font.setBold(false);
        font.setItalic(false);
        font.setWeight(50);
        lineEdit_window->setFont(font);
        lineEdit_window->setFrame(false);
        pushButton_u = new QPushButton(Dialog);
        pushButton_u->setObjectName(QStringLiteral("pushButton_u"));
        pushButton_u->setGeometry(QRect(490, 200, 70, 70));
        pushButton_u->setMinimumSize(QSize(0, 70));
        pushButton_u->setFont(font);
        pushButton_t = new QPushButton(Dialog);
        pushButton_t->setObjectName(QStringLiteral("pushButton_t"));
        pushButton_t->setGeometry(QRect(350, 200, 70, 70));
        pushButton_t->setMinimumSize(QSize(0, 70));
        pushButton_t->setFont(font);
        pushButton_y = new QPushButton(Dialog);
        pushButton_y->setObjectName(QStringLiteral("pushButton_y"));
        pushButton_y->setGeometry(QRect(420, 200, 70, 70));
        pushButton_y->setMinimumSize(QSize(0, 70));
        pushButton_y->setFont(font);
        pushButton_i = new QPushButton(Dialog);
        pushButton_i->setObjectName(QStringLiteral("pushButton_i"));
        pushButton_i->setGeometry(QRect(560, 200, 70, 70));
        pushButton_i->setMinimumSize(QSize(0, 70));
        pushButton_i->setFont(font);
        pushButton_q = new QPushButton(Dialog);
        pushButton_q->setObjectName(QStringLiteral("pushButton_q"));
        pushButton_q->setGeometry(QRect(70, 200, 70, 70));
        pushButton_q->setMinimumSize(QSize(0, 70));
        pushButton_q->setFont(font);
        pushButton_zuokuo = new QPushButton(Dialog);
        pushButton_zuokuo->setObjectName(QStringLiteral("pushButton_zuokuo"));
        pushButton_zuokuo->setGeometry(QRect(770, 200, 70, 70));
        pushButton_zuokuo->setMinimumSize(QSize(0, 70));
        pushButton_zuokuo->setFont(font);
        pushButton_p = new QPushButton(Dialog);
        pushButton_p->setObjectName(QStringLiteral("pushButton_p"));
        pushButton_p->setGeometry(QRect(700, 200, 70, 70));
        pushButton_p->setMinimumSize(QSize(0, 70));
        pushButton_p->setFont(font);
        pushButton_r = new QPushButton(Dialog);
        pushButton_r->setObjectName(QStringLiteral("pushButton_r"));
        pushButton_r->setGeometry(QRect(280, 200, 70, 70));
        pushButton_r->setMinimumSize(QSize(0, 70));
        pushButton_r->setFont(font);
        pushButton_youkuo = new QPushButton(Dialog);
        pushButton_youkuo->setObjectName(QStringLiteral("pushButton_youkuo"));
        pushButton_youkuo->setGeometry(QRect(840, 200, 70, 70));
        pushButton_youkuo->setMinimumSize(QSize(0, 70));
        pushButton_youkuo->setFont(font);
        pushButton_w = new QPushButton(Dialog);
        pushButton_w->setObjectName(QStringLiteral("pushButton_w"));
        pushButton_w->setGeometry(QRect(140, 200, 70, 70));
        pushButton_w->setMinimumSize(QSize(0, 70));
        pushButton_w->setFont(font);
        pushButton_o = new QPushButton(Dialog);
        pushButton_o->setObjectName(QStringLiteral("pushButton_o"));
        pushButton_o->setGeometry(QRect(630, 200, 70, 70));
        pushButton_o->setMinimumSize(QSize(0, 70));
        pushButton_o->setFont(font);
        pushButton_e = new QPushButton(Dialog);
        pushButton_e->setObjectName(QStringLiteral("pushButton_e"));
        pushButton_e->setGeometry(QRect(210, 200, 70, 70));
        pushButton_e->setMinimumSize(QSize(0, 70));
        pushButton_e->setFont(font);
        pushButton_j = new QPushButton(Dialog);
        pushButton_j->setObjectName(QStringLiteral("pushButton_j"));
        pushButton_j->setGeometry(QRect(495, 270, 70, 70));
        pushButton_j->setMinimumSize(QSize(0, 70));
        pushButton_j->setFont(font);
        pushButton_g = new QPushButton(Dialog);
        pushButton_g->setObjectName(QStringLiteral("pushButton_g"));
        pushButton_g->setGeometry(QRect(355, 270, 70, 70));
        pushButton_g->setMinimumSize(QSize(0, 70));
        pushButton_g->setFont(font);
        pushButton_h = new QPushButton(Dialog);
        pushButton_h->setObjectName(QStringLiteral("pushButton_h"));
        pushButton_h->setGeometry(QRect(425, 270, 70, 70));
        pushButton_h->setMinimumSize(QSize(0, 70));
        pushButton_h->setFont(font);
        pushButton_k = new QPushButton(Dialog);
        pushButton_k->setObjectName(QStringLiteral("pushButton_k"));
        pushButton_k->setGeometry(QRect(565, 270, 70, 70));
        pushButton_k->setMinimumSize(QSize(0, 70));
        pushButton_k->setFont(font);
        pushButton_a = new QPushButton(Dialog);
        pushButton_a->setObjectName(QStringLiteral("pushButton_a"));
        pushButton_a->setGeometry(QRect(75, 270, 70, 70));
        pushButton_a->setMinimumSize(QSize(0, 70));
        pushButton_a->setFont(font);
        pushButton_quote = new QPushButton(Dialog);
        pushButton_quote->setObjectName(QStringLiteral("pushButton_quote"));
        pushButton_quote->setGeometry(QRect(775, 270, 70, 70));
        pushButton_quote->setMinimumSize(QSize(0, 70));
        pushButton_quote->setFont(font);
        pushButton_semicolon = new QPushButton(Dialog);
        pushButton_semicolon->setObjectName(QStringLiteral("pushButton_semicolon"));
        pushButton_semicolon->setGeometry(QRect(705, 270, 70, 70));
        pushButton_semicolon->setMinimumSize(QSize(0, 70));
        pushButton_semicolon->setFont(font);
        pushButton_f = new QPushButton(Dialog);
        pushButton_f->setObjectName(QStringLiteral("pushButton_f"));
        pushButton_f->setGeometry(QRect(285, 270, 70, 70));
        pushButton_f->setMinimumSize(QSize(0, 70));
        pushButton_f->setFont(font);
        pushButton_enter = new QPushButton(Dialog);
        pushButton_enter->setObjectName(QStringLiteral("pushButton_enter"));
        pushButton_enter->setGeometry(QRect(845, 270, 130, 70));
        pushButton_enter->setMinimumSize(QSize(0, 70));
        pushButton_enter->setFont(font);
        pushButton_s = new QPushButton(Dialog);
        pushButton_s->setObjectName(QStringLiteral("pushButton_s"));
        pushButton_s->setGeometry(QRect(145, 270, 70, 70));
        pushButton_s->setMinimumSize(QSize(0, 70));
        pushButton_s->setFont(font);
        pushButton_l = new QPushButton(Dialog);
        pushButton_l->setObjectName(QStringLiteral("pushButton_l"));
        pushButton_l->setGeometry(QRect(635, 270, 70, 70));
        pushButton_l->setMinimumSize(QSize(0, 70));
        pushButton_l->setFont(font);
        pushButton_d = new QPushButton(Dialog);
        pushButton_d->setObjectName(QStringLiteral("pushButton_d"));
        pushButton_d->setGeometry(QRect(215, 270, 70, 70));
        pushButton_d->setMinimumSize(QSize(0, 70));
        pushButton_d->setFont(font);
        pushButton_m = new QPushButton(Dialog);
        pushButton_m->setObjectName(QStringLiteral("pushButton_m"));
        pushButton_m->setGeometry(QRect(570, 340, 70, 70));
        pushButton_m->setMinimumSize(QSize(0, 70));
        pushButton_m->setFont(font);
        pushButton_b = new QPushButton(Dialog);
        pushButton_b->setObjectName(QStringLiteral("pushButton_b"));
        pushButton_b->setGeometry(QRect(430, 340, 70, 70));
        pushButton_b->setMinimumSize(QSize(0, 70));
        pushButton_b->setFont(font);
        pushButton_n = new QPushButton(Dialog);
        pushButton_n->setObjectName(QStringLiteral("pushButton_n"));
        pushButton_n->setGeometry(QRect(500, 340, 70, 70));
        pushButton_n->setMinimumSize(QSize(0, 70));
        pushButton_n->setFont(font);
        pushButton_comma = new QPushButton(Dialog);
        pushButton_comma->setObjectName(QStringLiteral("pushButton_comma"));
        pushButton_comma->setGeometry(QRect(640, 340, 70, 70));
        pushButton_comma->setMinimumSize(QSize(0, 70));
        pushButton_comma->setFont(font);
        pushButton_z = new QPushButton(Dialog);
        pushButton_z->setObjectName(QStringLiteral("pushButton_z"));
        pushButton_z->setGeometry(QRect(150, 340, 70, 70));
        pushButton_z->setMinimumSize(QSize(0, 70));
        pushButton_z->setFont(font);
        pushButton_splash = new QPushButton(Dialog);
        pushButton_splash->setObjectName(QStringLiteral("pushButton_splash"));
        pushButton_splash->setGeometry(QRect(780, 340, 70, 70));
        pushButton_splash->setMinimumSize(QSize(0, 70));
        pushButton_splash->setFont(font);
        pushButton_v = new QPushButton(Dialog);
        pushButton_v->setObjectName(QStringLiteral("pushButton_v"));
        pushButton_v->setGeometry(QRect(360, 340, 70, 70));
        pushButton_v->setMinimumSize(QSize(0, 70));
        pushButton_v->setFont(font);
        pushButton_x = new QPushButton(Dialog);
        pushButton_x->setObjectName(QStringLiteral("pushButton_x"));
        pushButton_x->setGeometry(QRect(220, 340, 70, 70));
        pushButton_x->setMinimumSize(QSize(0, 70));
        pushButton_x->setFont(font);
        pushButton_period = new QPushButton(Dialog);
        pushButton_period->setObjectName(QStringLiteral("pushButton_period"));
        pushButton_period->setGeometry(QRect(710, 340, 70, 70));
        pushButton_period->setMinimumSize(QSize(0, 70));
        pushButton_period->setFont(font);
        pushButton_c = new QPushButton(Dialog);
        pushButton_c->setObjectName(QStringLiteral("pushButton_c"));
        pushButton_c->setGeometry(QRect(290, 340, 70, 70));
        pushButton_c->setMinimumSize(QSize(0, 70));
        pushButton_c->setFont(font);
        pushButton_shift = new QPushButton(Dialog);
        pushButton_shift->setObjectName(QStringLiteral("pushButton_shift"));
        pushButton_shift->setGeometry(QRect(80, 410, 145, 70));
        pushButton_shift->setMinimumSize(QSize(0, 70));
        pushButton_shift->setFont(font);
        pushButton_whitespace = new QPushButton(Dialog);
        pushButton_whitespace->setObjectName(QStringLiteral("pushButton_whitespace"));
        pushButton_whitespace->setGeometry(QRect(225, 410, 355, 70));
        pushButton_whitespace->setMinimumSize(QSize(0, 70));
        pushButton_whitespace->setFont(font);
        pushButton_up = new QPushButton(Dialog);
        pushButton_up->setObjectName(QStringLiteral("pushButton_up"));
        pushButton_up->setGeometry(QRect(850, 340, 70, 70));
        pushButton_up->setMinimumSize(QSize(0, 70));
        pushButton_up->setFont(font);
        pushButton_backsplash = new QPushButton(Dialog);
        pushButton_backsplash->setObjectName(QStringLiteral("pushButton_backsplash"));
        pushButton_backsplash->setGeometry(QRect(910, 200, 70, 70));
        pushButton_backsplash->setMinimumSize(QSize(0, 70));
        pushButton_backsplash->setFont(font);
        pushButton_left = new QPushButton(Dialog);
        pushButton_left->setObjectName(QStringLiteral("pushButton_left"));
        pushButton_left->setGeometry(QRect(780, 410, 70, 70));
        pushButton_left->setMinimumSize(QSize(0, 70));
        pushButton_left->setFont(font);
        pushButton_right = new QPushButton(Dialog);
        pushButton_right->setObjectName(QStringLiteral("pushButton_right"));
        pushButton_right->setGeometry(QRect(920, 410, 70, 70));
        pushButton_right->setMinimumSize(QSize(0, 70));
        pushButton_right->setFont(font);
        pushButton_down = new QPushButton(Dialog);
        pushButton_down->setObjectName(QStringLiteral("pushButton_down"));
        pushButton_down->setGeometry(QRect(850, 410, 70, 70));
        pushButton_down->setMinimumSize(QSize(0, 70));
        pushButton_down->setFont(font);
        pushButton_n2 = new QPushButton(Dialog);
        pushButton_n2->setObjectName(QStringLiteral("pushButton_n2"));
        pushButton_n2->setGeometry(QRect(110, 130, 70, 70));
        pushButton_n2->setMinimumSize(QSize(70, 70));
        pushButton_n2->setFont(font);
        pushButton_n2->setFocusPolicy(Qt::ClickFocus);
        pushButton_is_hanzi = new QPushButton(Dialog);
        pushButton_is_hanzi->setObjectName(QStringLiteral("pushButton_is_hanzi"));
        pushButton_is_hanzi->setGeometry(QRect(580, 410, 70, 70));
        pushButton_is_hanzi->setMinimumSize(QSize(0, 70));
        pushButton_is_hanzi->setFont(font);
        pushButton_ok = new QPushButton(Dialog);
        pushButton_ok->setObjectName(QStringLiteral("pushButton_ok"));
        pushButton_ok->setGeometry(QRect(650, 410, 130, 70));
        pushButton_ok->setMinimumSize(QSize(0, 70));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(85, 87, 83, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        pushButton_ok->setPalette(palette);
        pushButton_ok->setFont(font);
        pushButton_hanzi_7 = new QPushButton(Dialog);
        pushButton_hanzi_7->setObjectName(QStringLiteral("pushButton_hanzi_7"));
        pushButton_hanzi_7->setGeometry(QRect(570, 60, 70, 70));
        pushButton_hanzi_7->setMinimumSize(QSize(70, 70));
        QFont font1;
        font1.setFamily(QStringLiteral("Noto Sans S Chinese"));
        font1.setPointSize(10);
        font1.setBold(false);
        font1.setItalic(false);
        font1.setWeight(50);
        pushButton_hanzi_7->setFont(font1);
        pushButton_hanzi_5 = new QPushButton(Dialog);
        pushButton_hanzi_5->setObjectName(QStringLiteral("pushButton_hanzi_5"));
        pushButton_hanzi_5->setGeometry(QRect(500, 60, 70, 70));
        pushButton_hanzi_5->setMinimumSize(QSize(70, 70));
        pushButton_hanzi_5->setFont(font1);
        pushButton_hanzi_6 = new QPushButton(Dialog);
        pushButton_hanzi_6->setObjectName(QStringLiteral("pushButton_hanzi_6"));
        pushButton_hanzi_6->setGeometry(QRect(640, 60, 70, 70));
        pushButton_hanzi_6->setMinimumSize(QSize(70, 70));
        pushButton_hanzi_6->setFont(font1);
        pushButton_hanzi_8 = new QPushButton(Dialog);
        pushButton_hanzi_8->setObjectName(QStringLiteral("pushButton_hanzi_8"));
        pushButton_hanzi_8->setGeometry(QRect(710, 60, 70, 70));
        pushButton_hanzi_8->setMinimumSize(QSize(70, 70));
        pushButton_hanzi_8->setFont(font1);
        pushButton_hanzi_4 = new QPushButton(Dialog);
        pushButton_hanzi_4->setObjectName(QStringLiteral("pushButton_hanzi_4"));
        pushButton_hanzi_4->setGeometry(QRect(430, 60, 70, 70));
        pushButton_hanzi_4->setMinimumSize(QSize(70, 70));
        pushButton_hanzi_4->setFont(font1);
        pushButton_hanzi_2 = new QPushButton(Dialog);
        pushButton_hanzi_2->setObjectName(QStringLiteral("pushButton_hanzi_2"));
        pushButton_hanzi_2->setGeometry(QRect(290, 60, 70, 70));
        pushButton_hanzi_2->setMinimumSize(QSize(70, 70));
        pushButton_hanzi_2->setFont(font1);
        pushButton_hanzi_3 = new QPushButton(Dialog);
        pushButton_hanzi_3->setObjectName(QStringLiteral("pushButton_hanzi_3"));
        pushButton_hanzi_3->setGeometry(QRect(360, 60, 70, 70));
        pushButton_hanzi_3->setMinimumSize(QSize(70, 70));
        pushButton_hanzi_3->setFont(font1);
        pushButton_hanzi_left = new QPushButton(Dialog);
        pushButton_hanzi_left->setObjectName(QStringLiteral("pushButton_hanzi_left"));
        pushButton_hanzi_left->setGeometry(QRect(150, 60, 70, 70));
        pushButton_hanzi_left->setMinimumSize(QSize(70, 70));
        pushButton_hanzi_left->setFont(font);
        pushButton_hanzi_right = new QPushButton(Dialog);
        pushButton_hanzi_right->setObjectName(QStringLiteral("pushButton_hanzi_right"));
        pushButton_hanzi_right->setGeometry(QRect(780, 60, 70, 70));
        pushButton_hanzi_right->setMinimumSize(QSize(70, 70));
        pushButton_hanzi_right->setFont(font);
        pushButton_hanzi_1 = new QPushButton(Dialog);
        pushButton_hanzi_1->setObjectName(QStringLiteral("pushButton_hanzi_1"));
        pushButton_hanzi_1->setGeometry(QRect(220, 60, 70, 70));
        pushButton_hanzi_1->setMinimumSize(QSize(70, 70));
        pushButton_hanzi_1->setFont(font1);
        lineEdit_pinyin = new QLineEdit(Dialog);
        lineEdit_pinyin->setObjectName(QStringLiteral("lineEdit_pinyin"));
        lineEdit_pinyin->setGeometry(QRect(671, 0, 180, 60));
        lineEdit_pinyin->setMinimumSize(QSize(0, 60));
        lineEdit_pinyin->setFont(font);
        lineEdit_pinyin->setFrame(false);
        pushButton_n3 = new QPushButton(Dialog);
        pushButton_n3->setObjectName(QStringLiteral("pushButton_n3"));
        pushButton_n3->setGeometry(QRect(180, 130, 70, 70));
        pushButton_n3->setMinimumSize(QSize(70, 70));
        pushButton_n3->setFont(font);
        pushButton_backspace = new QPushButton(Dialog);
        pushButton_backspace->setObjectName(QStringLiteral("pushButton_backspace"));
        pushButton_backspace->setGeometry(QRect(880, 130, 111, 70));
        pushButton_backspace->setMinimumSize(QSize(70, 70));
        pushButton_backspace->setFont(font);
        pushButton_n0 = new QPushButton(Dialog);
        pushButton_n0->setObjectName(QStringLiteral("pushButton_n0"));
        pushButton_n0->setGeometry(QRect(670, 130, 70, 70));
        pushButton_n0->setMinimumSize(QSize(70, 70));
        pushButton_n0->setFont(font);
        pushButton_n1 = new QPushButton(Dialog);
        pushButton_n1->setObjectName(QStringLiteral("pushButton_n1"));
        pushButton_n1->setGeometry(QRect(40, 130, 70, 70));
        pushButton_n1->setMinimumSize(QSize(70, 70));
        pushButton_n1->setFont(font);
        pushButton_n1->setFocusPolicy(Qt::ClickFocus);
        pushButton_n6 = new QPushButton(Dialog);
        pushButton_n6->setObjectName(QStringLiteral("pushButton_n6"));
        pushButton_n6->setGeometry(QRect(390, 130, 70, 70));
        pushButton_n6->setMinimumSize(QSize(70, 70));
        pushButton_n6->setFont(font);
        pushButton_deng = new QPushButton(Dialog);
        pushButton_deng->setObjectName(QStringLiteral("pushButton_deng"));
        pushButton_deng->setGeometry(QRect(810, 130, 70, 70));
        pushButton_deng->setMinimumSize(QSize(70, 70));
        pushButton_deng->setFont(font);
        pushButton_gang = new QPushButton(Dialog);
        pushButton_gang->setObjectName(QStringLiteral("pushButton_gang"));
        pushButton_gang->setGeometry(QRect(740, 130, 70, 70));
        pushButton_gang->setMinimumSize(QSize(70, 70));
        pushButton_gang->setFont(font);
        pushButton_n5 = new QPushButton(Dialog);
        pushButton_n5->setObjectName(QStringLiteral("pushButton_n5"));
        pushButton_n5->setGeometry(QRect(320, 130, 70, 70));
        pushButton_n5->setMinimumSize(QSize(70, 70));
        pushButton_n5->setFont(font);
        pushButton_n7 = new QPushButton(Dialog);
        pushButton_n7->setObjectName(QStringLiteral("pushButton_n7"));
        pushButton_n7->setGeometry(QRect(460, 130, 70, 70));
        pushButton_n7->setMinimumSize(QSize(70, 70));
        pushButton_n7->setFont(font);
        pushButton_n8 = new QPushButton(Dialog);
        pushButton_n8->setObjectName(QStringLiteral("pushButton_n8"));
        pushButton_n8->setGeometry(QRect(530, 130, 70, 70));
        pushButton_n8->setMinimumSize(QSize(70, 70));
        pushButton_n8->setFont(font);
        pushButton_n4 = new QPushButton(Dialog);
        pushButton_n4->setObjectName(QStringLiteral("pushButton_n4"));
        pushButton_n4->setGeometry(QRect(250, 130, 70, 70));
        pushButton_n4->setMinimumSize(QSize(70, 70));
        pushButton_n4->setFont(font);
        pushButton_n9 = new QPushButton(Dialog);
        pushButton_n9->setObjectName(QStringLiteral("pushButton_n9"));
        pushButton_n9->setGeometry(QRect(600, 130, 70, 70));
        pushButton_n9->setMinimumSize(QSize(70, 70));
        pushButton_n9->setFont(font);
        QWidget::setTabOrder(pushButton_hanzi_left, pushButton_hanzi_1);
        QWidget::setTabOrder(pushButton_hanzi_1, pushButton_hanzi_2);
        QWidget::setTabOrder(pushButton_hanzi_2, pushButton_hanzi_3);
        QWidget::setTabOrder(pushButton_hanzi_3, pushButton_hanzi_4);
        QWidget::setTabOrder(pushButton_hanzi_4, pushButton_hanzi_5);
        QWidget::setTabOrder(pushButton_hanzi_5, pushButton_hanzi_6);
        QWidget::setTabOrder(pushButton_hanzi_6, pushButton_hanzi_7);
        QWidget::setTabOrder(pushButton_hanzi_7, pushButton_hanzi_8);
        QWidget::setTabOrder(pushButton_hanzi_8, pushButton_hanzi_right);
        QWidget::setTabOrder(pushButton_hanzi_right, pushButton_n1);
        QWidget::setTabOrder(pushButton_n1, pushButton_n2);
        QWidget::setTabOrder(pushButton_n2, pushButton_n3);
        QWidget::setTabOrder(pushButton_n3, pushButton_n4);
        QWidget::setTabOrder(pushButton_n4, pushButton_n5);
        QWidget::setTabOrder(pushButton_n5, pushButton_n6);
        QWidget::setTabOrder(pushButton_n6, pushButton_n7);
        QWidget::setTabOrder(pushButton_n7, pushButton_n8);
        QWidget::setTabOrder(pushButton_n8, pushButton_n9);
        QWidget::setTabOrder(pushButton_n9, pushButton_n0);
        QWidget::setTabOrder(pushButton_n0, pushButton_gang);
        QWidget::setTabOrder(pushButton_gang, pushButton_deng);
        QWidget::setTabOrder(pushButton_deng, pushButton_backspace);
        QWidget::setTabOrder(pushButton_backspace, pushButton_q);
        QWidget::setTabOrder(pushButton_q, pushButton_w);
        QWidget::setTabOrder(pushButton_w, pushButton_e);
        QWidget::setTabOrder(pushButton_e, pushButton_r);
        QWidget::setTabOrder(pushButton_r, pushButton_t);
        QWidget::setTabOrder(pushButton_t, pushButton_y);
        QWidget::setTabOrder(pushButton_y, pushButton_u);
        QWidget::setTabOrder(pushButton_u, pushButton_i);
        QWidget::setTabOrder(pushButton_i, pushButton_o);
        QWidget::setTabOrder(pushButton_o, pushButton_p);
        QWidget::setTabOrder(pushButton_p, pushButton_zuokuo);
        QWidget::setTabOrder(pushButton_zuokuo, pushButton_youkuo);
        QWidget::setTabOrder(pushButton_youkuo, pushButton_backsplash);
        QWidget::setTabOrder(pushButton_backsplash, pushButton_a);
        QWidget::setTabOrder(pushButton_a, pushButton_s);
        QWidget::setTabOrder(pushButton_s, pushButton_d);
        QWidget::setTabOrder(pushButton_d, pushButton_f);
        QWidget::setTabOrder(pushButton_f, pushButton_g);
        QWidget::setTabOrder(pushButton_g, pushButton_h);
        QWidget::setTabOrder(pushButton_h, pushButton_j);
        QWidget::setTabOrder(pushButton_j, pushButton_k);
        QWidget::setTabOrder(pushButton_k, pushButton_l);
        QWidget::setTabOrder(pushButton_l, pushButton_semicolon);
        QWidget::setTabOrder(pushButton_semicolon, pushButton_quote);
        QWidget::setTabOrder(pushButton_quote, pushButton_enter);
        QWidget::setTabOrder(pushButton_enter, pushButton_z);
        QWidget::setTabOrder(pushButton_z, pushButton_x);
        QWidget::setTabOrder(pushButton_x, pushButton_c);
        QWidget::setTabOrder(pushButton_c, pushButton_v);
        QWidget::setTabOrder(pushButton_v, pushButton_b);
        QWidget::setTabOrder(pushButton_b, pushButton_n);
        QWidget::setTabOrder(pushButton_n, pushButton_m);
        QWidget::setTabOrder(pushButton_m, pushButton_comma);
        QWidget::setTabOrder(pushButton_comma, pushButton_period);
        QWidget::setTabOrder(pushButton_period, pushButton_splash);
        QWidget::setTabOrder(pushButton_splash, pushButton_shift);
        QWidget::setTabOrder(pushButton_shift, pushButton_whitespace);
        QWidget::setTabOrder(pushButton_whitespace, pushButton_is_hanzi);
        QWidget::setTabOrder(pushButton_is_hanzi, pushButton_ok);
        QWidget::setTabOrder(pushButton_ok, pushButton_left);
        QWidget::setTabOrder(pushButton_left, pushButton_down);
        QWidget::setTabOrder(pushButton_down, pushButton_right);
        QWidget::setTabOrder(pushButton_right, pushButton_up);
        QWidget::setTabOrder(pushButton_up, lineEdit_pinyin);
        QWidget::setTabOrder(lineEdit_pinyin, lineEdit_window);

        retranslateUi(Dialog);

        QMetaObject::connectSlotsByName(Dialog);
    } // setupUi

    void retranslateUi(QDialog *Dialog)
    {
        Dialog->setWindowTitle(QApplication::translate("Dialog", "Dialog", nullptr));
        lineEdit_window->setText(QString());
        pushButton_u->setText(QApplication::translate("Dialog", "u", nullptr));
        pushButton_t->setText(QApplication::translate("Dialog", "t", nullptr));
        pushButton_y->setText(QApplication::translate("Dialog", "y", nullptr));
        pushButton_i->setText(QApplication::translate("Dialog", "i", nullptr));
        pushButton_q->setText(QApplication::translate("Dialog", "q", nullptr));
        pushButton_zuokuo->setText(QApplication::translate("Dialog", "[", nullptr));
        pushButton_p->setText(QApplication::translate("Dialog", "p", nullptr));
        pushButton_r->setText(QApplication::translate("Dialog", "r", nullptr));
        pushButton_youkuo->setText(QApplication::translate("Dialog", "]", nullptr));
        pushButton_w->setText(QApplication::translate("Dialog", "w", nullptr));
        pushButton_o->setText(QApplication::translate("Dialog", "o", nullptr));
        pushButton_e->setText(QApplication::translate("Dialog", "e", nullptr));
        pushButton_j->setText(QApplication::translate("Dialog", "j", nullptr));
        pushButton_g->setText(QApplication::translate("Dialog", "g", nullptr));
        pushButton_h->setText(QApplication::translate("Dialog", "h", nullptr));
        pushButton_k->setText(QApplication::translate("Dialog", "k", nullptr));
        pushButton_a->setText(QApplication::translate("Dialog", "a", nullptr));
        pushButton_quote->setText(QApplication::translate("Dialog", "'", nullptr));
        pushButton_semicolon->setText(QApplication::translate("Dialog", ";", nullptr));
        pushButton_f->setText(QApplication::translate("Dialog", "f", nullptr));
        pushButton_enter->setText(QApplication::translate("Dialog", "enter", nullptr));
        pushButton_s->setText(QApplication::translate("Dialog", "s", nullptr));
        pushButton_l->setText(QApplication::translate("Dialog", "l", nullptr));
        pushButton_d->setText(QApplication::translate("Dialog", "d", nullptr));
        pushButton_m->setText(QApplication::translate("Dialog", "m", nullptr));
        pushButton_b->setText(QApplication::translate("Dialog", "b", nullptr));
        pushButton_n->setText(QApplication::translate("Dialog", "n", nullptr));
        pushButton_comma->setText(QApplication::translate("Dialog", ",", nullptr));
        pushButton_z->setText(QApplication::translate("Dialog", "z", nullptr));
        pushButton_splash->setText(QApplication::translate("Dialog", "/", nullptr));
        pushButton_v->setText(QApplication::translate("Dialog", "v", nullptr));
        pushButton_x->setText(QApplication::translate("Dialog", "x", nullptr));
        pushButton_period->setText(QApplication::translate("Dialog", ".", nullptr));
        pushButton_c->setText(QApplication::translate("Dialog", "c", nullptr));
        pushButton_shift->setText(QApplication::translate("Dialog", "shift", nullptr));
        pushButton_whitespace->setText(QString());
        pushButton_up->setText(QApplication::translate("Dialog", "\342\206\221", nullptr));
        pushButton_backsplash->setText(QApplication::translate("Dialog", "\\", nullptr));
        pushButton_left->setText(QApplication::translate("Dialog", "\342\206\220", nullptr));
        pushButton_right->setText(QApplication::translate("Dialog", "\342\206\222", nullptr));
        pushButton_down->setText(QApplication::translate("Dialog", "\342\206\223", nullptr));
        pushButton_n2->setText(QApplication::translate("Dialog", "2", nullptr));
        pushButton_is_hanzi->setText(QApplication::translate("Dialog", "Eng", nullptr));
        pushButton_ok->setText(QApplication::translate("Dialog", "OK", nullptr));
        pushButton_hanzi_7->setText(QString());
        pushButton_hanzi_5->setText(QString());
        pushButton_hanzi_6->setText(QString());
        pushButton_hanzi_8->setText(QString());
        pushButton_hanzi_4->setText(QString());
        pushButton_hanzi_2->setText(QString());
        pushButton_hanzi_3->setText(QString());
        pushButton_hanzi_left->setText(QApplication::translate("Dialog", "\342\206\220", nullptr));
        pushButton_hanzi_right->setText(QApplication::translate("Dialog", "\342\206\222", nullptr));
        pushButton_hanzi_1->setText(QString());
        lineEdit_pinyin->setText(QString());
        pushButton_n3->setText(QApplication::translate("Dialog", "3", nullptr));
        pushButton_backspace->setText(QApplication::translate("Dialog", "<-", nullptr));
        pushButton_n0->setText(QApplication::translate("Dialog", "0", nullptr));
        pushButton_n1->setText(QApplication::translate("Dialog", "1", nullptr));
        pushButton_n6->setText(QApplication::translate("Dialog", "6", nullptr));
        pushButton_deng->setText(QApplication::translate("Dialog", "=", nullptr));
        pushButton_gang->setText(QApplication::translate("Dialog", "-", nullptr));
        pushButton_n5->setText(QApplication::translate("Dialog", "5", nullptr));
        pushButton_n7->setText(QApplication::translate("Dialog", "7", nullptr));
        pushButton_n8->setText(QApplication::translate("Dialog", "8", nullptr));
        pushButton_n4->setText(QApplication::translate("Dialog", "4", nullptr));
        pushButton_n9->setText(QApplication::translate("Dialog", "9", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Dialog: public Ui_Dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SYSZUXPINYIN_H
