DATAS SEGMENT
    STATUE DB 0 
DATAS ENDS

STACKS SEGMENT
    DW 100 DUP(?)
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES, DS:DATAS, SS:STACKS
START:
    MOV AX, DATAS
    MOV DS, AX

    ; 取STATUE中的字节进行测试
    MOV AL, STATUE
    AND AL, 00101010B ; 只保留第1、3、5位
    CMP AL, 00101010B ; 检查这三位是否全为1
    JE ROUTINE_1
    CMP AL, 00010100B ; 检查这三位是否有两位为1
    JE ROUTINE_2
    CMP AL, 00000010B ; 检查这三位是否只有一位为1
    JE ROUTINE_3
    JMP ROUTINE_4

ROUTINE_1:
    ; ROUTINE_1的代码
    JMP END_PROGRAM

ROUTINE_2:
    ; ROUTINE_2的代码
    JMP END_PROGRAM

ROUTINE_3:
    ; ROUTINE_3的代码
    JMP END_PROGRAM

ROUTINE_4:
    ; ROUTINE_4的代码

END_PROGRAM:
    MOV AH, 4CH
    INT 21H
CODES ENDS
    END START
