LOGICAL MACRO OP, REG1, REG2
    &OP &REG1, &REG2
ENDM

DATA SEGMENT
    VALUE1 DW 0F0Fh  
    VALUE2 DW 0A0A0h  
    RESULT DW ?       
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE, DS:DATA

START:
    MOV AX, DATA    
    MOV DS, AX

    MOV AX, VALUE1       ; 加载第一个值到 AX
    MOV BX, VALUE2       ; 加载第二个值到 BX

    ; 使用 LOGICAL 宏
    LOGICAL AND, AX, BX  ; 执行 AX = AX AND BX
    MOV RESULT, AX       ; 将结果存储到 RESULT

    LOGICAL OR, AX, BX   ;  AX = AX OR BX
    LOGICAL XOR, AX, BX  ; AX = AX XOR BX
    LOGICAL TEST, AX, BX

    ; 结束程序
    MOV AH, 4CH
    INT 21H

CODE ENDS
    END START

