webtalk_init -webtalk_dir C:/DigitalLogic/EGO1/example_6_5_EGO1/example_6_5_EGO1.sim/sim_1/behav/xsim/xsim.dir/example_6_5_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 19 20:12:15 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c63c1611-9fc9-4216-9626-47eb0d061915" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5d96ffea28374faeb58571f48e97dc70" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 Microsoft Surface (R) Edition" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2296 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "15.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "180 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7156_KB" -context "xsim\\usage"
webtalk_transmit -clientid 48532450 -regid "" -xml C:/DigitalLogic/EGO1/example_6_5_EGO1/example_6_5_EGO1.sim/sim_1/behav/xsim/xsim.dir/example_6_5_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/DigitalLogic/EGO1/example_6_5_EGO1/example_6_5_EGO1.sim/sim_1/behav/xsim/xsim.dir/example_6_5_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/DigitalLogic/EGO1/example_6_5_EGO1/example_6_5_EGO1.sim/sim_1/behav/xsim/xsim.dir/example_6_5_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
