# 基础配置（非敏感信息）
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.re0hg.backend.pojo

# 阿里云OSS配置（使用环境变量）
aliyun:
  oss:
    accessKeyId: ${ALIYUN_OSS_ACCESS_KEY_ID:your-default-dev-key}
    accessKeySecret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:your-default-dev-secret}
    bucketName: ${ALIYUN_OSS_BUCKET_NAME:your-dev-bucket}
    endpoint: ${ALIYUN_OSS_ENDPOINT:https://oss-cn-hangzhou.aliyuncs.com}

# Spring配置
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/personal_courses_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:00000000}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: smtp.qq.com
    port: 465  #(SSL)
    username: 1375803462@qq.com
    password: zmddnwfatldzhgbh  # 授权码
    protocol: smtp
    properties:
      mail.smtp:
        auth: true
        ssl.enable: true  # 必须开启SSL
        starttls.enable: false  # 如果使用465端口则关闭STARTTLS
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
    default-encoding: UTF-8

# Spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
