webtalk_init -webtalk_dir C:/Users/21211/Desktop/example_6_4_2_EGO1/example_6_4_2_EGO1.sim/sim_1/behav/xsim/xsim.dir/example_6_4_2_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 16 20:41:38 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b9e6c560-e05d-4587-a767-600a361ec29f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a9c76ec824d24813b4b3b02f5c175a72" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) Ultra 5 125H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1800000016500 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8448_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3827246232 -regid "" -xml C:/Users/21211/Desktop/example_6_4_2_EGO1/example_6_4_2_EGO1.sim/sim_1/behav/xsim/xsim.dir/example_6_4_2_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/21211/Desktop/example_6_4_2_EGO1/example_6_4_2_EGO1.sim/sim_1/behav/xsim/xsim.dir/example_6_4_2_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/21211/Desktop/example_6_4_2_EGO1/example_6_4_2_EGO1.sim/sim_1/behav/xsim/xsim.dir/example_6_4_2_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
